name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: self-hosted


    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run:
         npm i
    - run:
          cd ui
    - run:
          npm i
    - run:
          npm build
    - run:
          cd ..
    - run:
          pm2 stop 0
    - run:
          pm2 start 0
    - run:
          pm2 save
    - run:
          echo "Auto" | sudo -S service nginx restart
